### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by rwhat** [DevBlocky/radar#1]
Is there anyway to make the black background of radar clear instead of black?

**Comment by rwhat** [comment]
btw I am enjoying the scripts you make...using the emote script...

**Comment by DevBlocky** [comment]
Line [147](https://github.com/blockba5her/radar/blob/master/resources/radar/radar.lua#L147) of the radar `cl.lua` file, change the `255` to a lower number to change it's transparency.

**Comment by rwhat** [comment]
Thank you sir!

**Comment by rwhat** [comment]
If you get time, would be willing to email me directly in regards to
possibly helping me with some custom scripts? I would donate for them...
