### ISSUE TITLE
Change Open Key

### ISSUE THREAD

**Issue by rwhat** [DevBlocky/radar#2]
I thought i found the spot for it, but was wrong....how would I change the key bind for the radar open...we use controller for gameplay and the left on dpad opens radar and lights.....need to remap key somehow. Thanks and love the RADAR!!

**Comment by DevBlocky** [comment]
You can check out [this website](https://wiki.fivem.net/wiki/Controls) for all of the key codes for the game (don't worry about the top indexes)

The button press logic starts at line [204](https://github.com/blockba5her/radar/blob/master/resources/radar/radar.lua#L204) and ends at 215.

If you have any other questions then go ahead and comment on this issue, for now I'm closing the issue.
